#include<bits\stdc++.h>
using namespace std;


int main(){

    // string name;
    // name.push_back('a');
//    cin>>name;
//    cout<<name;

// name[3];
// name.push_back('a');
// cout<<name;

// string lala;
// getline(cin,lala,'A');
// cout<<lala;

// string name ="Maharana Pratap";
// cout<<name[0]<<endl;
// cout<<name.at(0)<<endl;
// cout<<name.front()<<endl;
// cout<<name.back()<<endl;
// cout<<name.length()<<endl; //15

// auto it= name.begin();
// while(it != name.end()){
//     cout<< *it <<" ";
//     it++;
// }
// cout<<endl;

// cout<<name;

// string fname = "Love";
// string lname = "Babbar";
// string ans = fname+lname;
// cout<<ans;

// string str = "Hello Jee";
// cout<<str.substr(0,5);
// cout<<endl;
// cout<<str.substr(0);

// string name = "Hello kaise";
// string word = " aise";
// // int ans = name.find(word);
// // cout<< ans<<endl;

// if(name.find(word) != string::npos){
//     cout<<"found";
// }
// else{
//     cout<<"not found";
// }

string s1 ="love";
string s2 ="love";
cout<<s1.compare(s2)<<endl;



}